apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookstore
  template:
    metadata:
      labels:
        app: bookstore
    spec:
      containers:
      - name: bookstore
        image: vamshidhar1128/bookstore
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-service
spec:
  type: LoadBalancer
  selector:
    app: bookstore
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
